name: CI
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: 6.11.1
        host: linux
        target: desktop

    - name: CMake Build
      run: |
        git fetch origin master
        cmake -B bin -DBUILD_DOC=ON -DBUILD_PACKAGE=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_SIGNED=OFF -DBUILD_TESTING=ON -DTEST_TERMINAL=OFF -DCMAKE_BUILD_TYPE=Release .
        cmake --build bin --target tst_libmacro
        cmake --build bin --target doxygen || true

    - name: tst_libmacro
      run: bin/tst_libmacro

    - name: Upload Docs
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: bin/doxygen/html/

